spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/wejump
    username: root
    password: root
#    url: jdbc:mariadb://wejump.cglhadxlzhnk.ap-northeast-2.rds.amazonaws.com:3306/innodb
#    username: admin
#    password: jump772772
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.MariaDB103Dialect
#      ddl-auto: update
      ddl-auto: create
    show_sql: true
  profiles:
    include: oauth

file:
  upload:
    path:
      C:\Users\miles\OneDrive\Desktop\2023_activity\weJump