server:
  port: 8080

spring:
  datasource:
    driver_class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/wejump
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect


