server:
  port: 8080

spring:
  profiles:
    active: docker
  datasource:
    driver_class-name: org.mariadb.jdbc.Driver

    url: jdbc:mariadb://localhost:3306/wejump
    username: root
    password: 7213


    #url: jdbc:mariadb://wejump.cglhadxlzhnk.ap-northeast-2.rds.amazonaws.com:3306/wejump
    #username: admin
    #password: wejump772772
  jpa:
    hibernate:
    database-platform: org.hibernate.dialect.MariaDB103Dialect